### ISSUE TITLE
Re-Activate Customer

### ISSUE THREAD

**Issue by SamSloboda** [CSCI-GA-2820-FA22-001/customers#15]
**As a** user
 **I need**  to be able to reactivate my profile
 **So that** I can resume using it after deactivation
   
 ### Details and Assumptions
 * The user is deactivated.
 * There is an isActivated field in the database.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given user unique ID
 When the reactivation process is requested
 Then the user should be active and able to use service as he was able before deactivation.
 ```

**Comment by Tazhio** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/customers-6333a59457678a0019763df8/issues/nyu-devops-fall22/customers/15?planning-poker) with Zenhub @SamSloboda @omb244 @kovidiament
