### ISSUE TITLE
Add Activate/Deactivate string support 

### ISSUE THREAD

**Issue by omb244** [CSCI-GA-2820-FA22-001/customers#37]
**As a** user
 **I need* to query customers by their active/deactive status
 **So that** I can query only active/deactive customers.
   
 ### Details and Assumptions
 * 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a query
 When the query include "active/deactive"
 Then list function will only return the according customers
 ```

**Comment by kovidiament** [comment]
This will add the ability to get a list of only "all customers whose active flags are set to true" or only "all customers whose active flags are set to false "
