### ISSUE TITLE
IBM Cloud Accounts Setup

### ISSUE THREAD

**Issue by omb244** [CSCI-GA-2820-FA22-001/customers#48]
**As a** developer
 **I need** to have a proper IBM cloud account setup
 **So that** we are able to deploy our application to a Kubernetes cluster.

   
 ### Details and Assumptions
 * Every team member is able to go through the registration guide and create their accounts
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given our development team
 We are all requesting access and working on the same Kubernetes cluster.
 
 ```

**Comment by SamSloboda** [comment]
Created a IBM Cloud Access Group and Invited all of you guys. Please check your emails and accept the invite. We will close the issue once all of the "Pending" invites, will turn to "Active".
<img width="1552" alt="Screenshot 2022-11-18 at 23 34 46" src="https://user-images.githubusercontent.com/61265048/202840238-a5927792-5d4c-4de5-910e-f52d14fa961d.png">

**Comment by SamSloboda** [comment]
<img width="1552" alt="Screenshot 2022-11-21 at 13 04 27" src="https://user-images.githubusercontent.com/61265048/203128076-8615b6a1-fc99-482c-aec8-9ce581bf05da.png">
