### ISSUE TITLE
IP/Production portal setup

### ISSUE THREAD

**Issue by omb244** [CSCI-GA-2820-FA22-001/customers#51]
**As a** developer
 **I need** to run our service as a NodePort and set our development port to **31001** and the Production port to
**31002**
 **So that** we have a common conventional port and to avoid confusion when other teams test our service.
   
 ### Details and Assumptions
 * Development port is: 31001 and the Production port is:
31002
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a tester
 When they request our service 
 Then the service should run without problems on the port intended
 ```

**Comment by SamSloboda** [comment]
Closing this issue as a duplicate. This will be included in the CD Pipeline Deploy Stage and Production Stage.
