### ISSUE TITLE
Add a /health endpoint to our service

### ISSUE THREAD

**Issue by omb244** [CSCI-GA-2820-FA22-001/customers#52]
**As a** developer
 **I need** the ability to check the "health" status of my Kubernetes cluster
 **So that** I am aware if our service is active or not
   
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a Kubernetes cluster
 When I request /health endpoint to our service it should return {"status":"OK},
200
 ```

**Comment by SamSloboda** [comment]
Hey Omar, this is a duplicate issue! I have already implemented this one in the previous issue. You can mark it as a duplicate and close it.
