### ISSUE TITLE
Set up the DevOps Continuous Delivery Pipeline

### ISSUE THREAD

**Issue by SamSloboda** [CSCI-GA-2820-FA22-001/customers#73]
**As a** developer
 **I need** Continuous Delivery Pipeline
 **So that** I can automatically deploy code to the production.
   
 ### Details and Assumptions
 * We will be using IBM Cloud Continuous Delivery Service.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by SamSloboda** [comment]
<img width="1440" alt="Screenshot 2022-11-26 at 21 52 10" src="https://user-images.githubusercontent.com/61265048/204117124-35da747c-e0db-42df-9051-db442dcbb408.png">

Toolchain created!

**Comment by SamSloboda** [comment]
<img width="1440" alt="Screenshot 2022-11-26 at 22 21 48" src="https://user-images.githubusercontent.com/61265048/204117758-8a102a09-d9ed-49da-9085-a2e368134b61.png">

**Comment by kovidiament** [comment]
lgtm
