### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by VincentCCCCCC** [CSCI-GA-2820-FA22-001/customers#9]
**As a** customer,
 **I need** the funtion to change my password,  
 **So that** I can protect my account and data
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by SamSloboda** [comment]
I think we should add some kind of verification that the password is different that the previous one, and that it is valid.
